use_frameworks!

platform :ios, '8.0'

target 'BModule_Example' do
  pod 'BModule', :path => '../'

  target 'BModule_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
